# Generated by Django 5.1.2 on 2024-10-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nit', models.AutoField(primary_key=True, serialize=False)),
                ('nom_empresa', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=60)),
                ('correo_emp', models.EmailField(max_length=50, unique=True)),
                ('password_emp', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_id', models.CharField(max_length=25)),
                ('nom_estudiante', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo_estudiante', models.EmailField(max_length=50, unique=True)),
                ('fecha_nac', models.DateField()),
                ('password_estudiante', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
