---SCRIPT PARA BORRAR LAS TABLAS---
DROP TABLE ESTUDIANTES;
DROP TABLE CERTIFICADOS;
DROP TABLE CURSOS;
DROP TABLE CURSOS_APROBADOS;
DROP TABLE CURSOS_FAVORITOS;
DROP TABLE  EMPRESAS;
DROP TABLE  OFERTAS_EMPLEOS;
DROP TABLE  PRUEBAS_ADMISIONES;
DROP TABLE  HOJAS_DE_VIDA;
DROP TABLE  LENGUAJES_PROG;
DROP TABLE  APTITUDES;
DROP TABLE  IDIOMAS;
DROP TABLE  FORMACIONES_ACADEMICAS;
DROP TABLE  EXP_LABORAL;



CREATE TABLE ESTUDIANTES
(ID_ESTUDIANTE NUMBER(10),
TIPO_ID CHAR(15),
NOM_ESTUDIANTE CHAR(50),
APELLIDO CHAR (50),
CORREO_ESTUDIANTE CHAR (50),
FECHA_NAC DATE,
PASSWORD_ESTUDIANTE CHAR(25));

-------------------------------
CREATE TABLE CERTIFICADOS
(ID_CERTIFICADO NUMBER(10),
ID_ESTUDIANTE NUMBER(10),
ID_CURSO NUMBER(10));

-------------------------------
CREATE TABLE CURSOS
(ID_CURSO NUMBER(10),
NOM_CURSO CHAR(50),
DIFICULTAD CHAR(10),
DESCRIPCION VARCHAR2(1000),
ID_ESTUDIANTE NUMBER(10));

-------------------------------
CREATE TABLE CURSOS_APROBADOS
(ID_PRUEBAADMIN NUMBER(10),
ID_CURSO NUMBER(10),
ID_ESTUDIANTE NUMBER(10));

-------------------------------
CREATE TABLE CURSOS_FAVORITOS
(ID_CURSO_FAVORITO NUMBER(10),
ID_CURSO NUMBER(10),
NIT NUMBER(10)
);

-------------------------------
CREATE TABLE EMPRESAS
(NIT NUMBER(25),
NOM_EMPRESA CHAR(50),
DIRECCION CHAR(60),
CORREO_EMP CHAR(20),
PASSWORD_EMP CHAR(25),
TELEFONO NUMBER(10));

-------------------------------
CREATE TABLE OFERTAS_EMPLEOS
(ID_OFERTA NUMBER(10),
ID_EMPRESA NUMBER(10),
NOMBRE_OFERTA CHAR(50),
DESCRIPCION VARCHAR2(1000),
CANT_APLICADOS NUMBER(3)
);

-------------------------------
CREATE TABLE PRUEBAS_ADMISIONES
(ID_PRUEBA NUMBER(10),
ID_EMPRESA NUMBER(10),
PREGUNTA1 CHAR(1000),
RESPUESTA1 CHAR(1000),
PREGUNTA2 CHAR(1000),
RESPUESTA2 CHAR(1000),
PREGUNTA3 CHAR(1000),
RESPUESTA3 CHAR(1000),
PREGUNTA4 CHAR(1000),
RESPUESTA4 CHAR(1000),
PREGUNTA5 CHAR(1000),
RESPUESTA5 CHAR(1000)
);
-------------------------------
CREATE TABLE HOJAS_DE_VIDA
(ID_HOJA_VIDA NUMBER(10),
ID_ESTUDIANTE NUMBER(10),
DESCRIPCION VARCHAR2(1000),
TELEFONO NUMBER(10),
DIRECCION CHAR(50));

------------------------------
CREATE TABLE LENGUAJES_PROG
(ID_LENGUAJE NUMBER(10),
ID_HOJAVIDA NUMBER(10),
NOMBRE_LENG CHAR(50));

-------------------------------
CREATE TABLE APTITUDES
(ID_APTITUDES NUMBER(10),
ID_HOJAVIDA NUMBER(10),
NOMBRE_APT CHAR(50));

-------------------------------
CREATE TABLE IDIOMAS
(ID_IDIOMA NUMBER(10),
ID_HOJAVIDA NUMBER(10),
IDIOMA CHAR(20),
NIVEL CHAR(20));

-------------------------------
CREATE TABLE FORMACIONES_CADEMICAS
(ID_FORMACION NUMBER(10),
ID_HOJAVIDA NUMBER(10),
NOM_INSTITUCION CHAR(50),
TITULO CHAR(50),
FECHA_INICIO DATE,
FECHA_FINAL DATE);

-------------------------------
CREATE TABLE EXP_LABORAL
(ID_EXP NUMBER(10),
ID_HOJAVIDA NUMBER(10),
NOM_EMPRESAS CHAR(50),
TIEMPO_INCIO DATE,
TIEMPO_FINAL DATE,
CARGO CHAR(30),
 DESCRIPCION VARCHAR2(1000);
