--- TIPO DE CONTRATO
INSERT INTO TIPO_CONT (ID_TIPO_CONT, NOMBRE_TIPO) VALUES (1, 'indefinido');
INSERT INTO TIPO_CONT (ID_TIPO_CONT, NOMBRE_TIPO) VALUES (2, 'fijo');
INSERT INTO TIPO_CONT (ID_TIPO_CONT, NOMBRE_TIPO) VALUES (3, 'obra');
INSERT INTO TIPO_CONT (ID_TIPO_CONT, NOMBRE_TIPO) VALUES (4, 'servicios');
INSERT INTO TIPO_CONT (ID_TIPO_CONT, NOMBRE_TIPO) VALUES (5, 'temporal');

--- CONTENIDO CURSO
INSERT INTO TIPO_CONTENIDO (ID_TIPO_CONTENIDO, NOMBRE_TIPO) VALUES (1, 'Html');

--- DIFICULTAD CURSO
INSERT INTO TIPO_DIFICULTAD (ID_TIPO_DIFICULTAD, NOMBRE_TIPO) VALUES (1, 'Básico');
INSERT INTO TIPO_DIFICULTAD (ID_TIPO_DIFICULTAD, NOMBRE_TIPO) VALUES (2, 'Medio');
INSERT INTO TIPO_DIFICULTAD (ID_TIPO_DIFICULTAD, NOMBRE_TIPO) VALUES (3, 'Avanzado');

--- DURACION CURSO
INSERT INTO TIPO_DURACION (ID_TIPO_DURACION, NOMBRE_TIPO) VALUES (1, '0-5 Horas');
INSERT INTO TIPO_DURACION (ID_TIPO_DURACION, NOMBRE_TIPO) VALUES (2, '6-10 Horas');
INSERT INTO TIPO_DURACION (ID_TIPO_DURACION, NOMBRE_TIPO) VALUES (3, '11-15 Horas');
INSERT INTO TIPO_DURACION (ID_TIPO_DURACION, NOMBRE_TIPO) VALUES (4, '15+ Horas');

--- CERTIFICADO CURSO
INSERT INTO TIPO_CERTIFICADO (ID_TIPO_CERTIFICADO, NOMBRE_TIPO) VALUES (1, 'Con certificado');
INSERT INTO TIPO_CERTIFICADO (ID_TIPO_CERTIFICADO, NOMBRE_TIPO) VALUES (2, 'Sin certificado');