---SECUENCIAS
CREATE SEQUENCE lenguajes_prog_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE aptitudes_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE idiomas_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE formaciones_academicas_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE exp_laborales_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE oferta_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE US_ADMIN_OCTOO.SEQ_ID_CONOCIMIENTO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE tipo_cont_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ofertas_disponibles_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE cursos_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE tipo_contenido_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE tipo_dificultad_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE tipo_duracion_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE tipo_certificado_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE cursos_disponibles_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE cursos_aprobados_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE contenidos_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE sub_contenidos_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE preguntas_curso_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE respuestas_curso_seq START WITH 1 INCREMENT BY 1;

----TRIGERS----
----LENGUAJES_PROG
CREATE OR REPLACE TRIGGER lenguajes_prog_trigger
BEFORE INSERT ON LENGUAJES_PROG
FOR EACH ROW
WHEN (NEW.ID_LENGUAJE IS NULL)
BEGIN
    SELECT lenguajes_prog_seq.NEXTVAL INTO :NEW.ID_LENGUAJE FROM dual;
END;

----APTITUDES
CREATE OR REPLACE TRIGGER aptitudes_trigger
BEFORE INSERT ON APTITUDES
FOR EACH ROW
WHEN (NEW.ID_APTITUDES IS NULL)
BEGIN
    SELECT aptitudes_seq.NEXTVAL INTO :NEW.ID_APTITUDES FROM dual;
END;

----IDIOMAS
CREATE OR REPLACE TRIGGER idiomas_trigger
BEFORE INSERT ON IDIOMAS
FOR EACH ROW
WHEN (NEW.ID_IDIOMA IS NULL)
BEGIN
    SELECT idiomas_seq.NEXTVAL INTO :NEW.ID_IDIOMA FROM dual;
END;

----FORMACIONES_ACADEMICAS
CREATE OR REPLACE TRIGGER formaciones_academicas_trigger
BEFORE INSERT ON FORMACIONES_ACADEMICAS
FOR EACH ROW
WHEN (NEW.ID_FORMACION IS NULL)
BEGIN
    SELECT formaciones_academicas_seq.NEXTVAL INTO :NEW.ID_FORMACION FROM dual;
END;

----EXP_LABORALES
CREATE OR REPLACE TRIGGER exp_laborales_trigger
BEFORE INSERT ON EXP_LABORALES
FOR EACH ROW
WHEN (NEW.ID_EXP IS NULL)
BEGIN
    SELECT exp_laborales_seq.NEXTVAL INTO :NEW.ID_EXP FROM dual;
END;

----OFERTAS_EMPLEOS
CREATE OR REPLACE TRIGGER oferta_id_trigger
BEFORE INSERT ON OFERTAS_EMPLEOS
FOR EACH ROW
WHEN (NEW.ID_OFERTA IS NULL)
BEGIN
    SELECT oferta_id_seq.NEXTVAL INTO :NEW.ID_OFERTA FROM dual;
END;

---CONOCIMIENTOS
CREATE OR REPLACE TRIGGER US_ADMIN_OCTOO.BI_CONOCIMIENTOS_ID
BEFORE INSERT ON US_ADMIN_OCTOO.CONOCIMIENTOS
FOR EACH ROW
BEGIN
    IF :NEW.ID_CONOCIMIENTO IS NULL THEN
        SELECT SEQ_ID_CONOCIMIENTO.NEXTVAL INTO :NEW.ID_CONOCIMIENTO FROM dual;
    END IF;
END;

---TIPO_CONT
CREATE OR REPLACE TRIGGER tipo_cont_trigger
BEFORE INSERT ON TIPO_CONT
FOR EACH ROW
WHEN (NEW.ID_TIPO_CONT IS NULL)
BEGIN
    SELECT tipo_cont_seq.NEXTVAL INTO :NEW.ID_TIPO_CONT FROM dual;
END;

----OFERTAS_DISPONIBLES
CREATE OR REPLACE TRIGGER ofertas_disponibles_trigger
BEFORE INSERT ON OFERTAS_DISPONIBLES
FOR EACH ROW
WHEN (NEW.ID_OFER_DISPONIBLE IS NULL)
BEGIN
    SELECT ofertas_disponibles_seq.NEXTVAL INTO :NEW.ID_OFER_DISPONIBLE FROM dual;
END;

----CURSOS
CREATE OR REPLACE TRIGGER cursos_trigger
BEFORE INSERT ON CURSOS
FOR EACH ROW
WHEN (NEW.ID_CURSO IS NULL)
BEGIN
    SELECT cursos_seq.NEXTVAL INTO :NEW.ID_CURSO FROM dual;
END;

----TIPO_CONTENIDO
CREATE OR REPLACE TRIGGER tipo_contenido_trigger
BEFORE INSERT ON TIPO_CONTENIDO
FOR EACH ROW
WHEN (NEW.ID_TIPO_CONTENIDO IS NULL)
BEGIN
    SELECT tipo_contenido_seq.NEXTVAL INTO :NEW.ID_TIPO_CONTENIDO FROM dual;
END;

----TIPO_DIFICULTAD
CREATE OR REPLACE TRIGGER tipo_dificultad_trigger
BEFORE INSERT ON TIPO_DIFICULTAD
FOR EACH ROW
WHEN (NEW.ID_TIPO_DIFICULTAD IS NULL)
BEGIN
    SELECT tipo_dificultad_seq.NEXTVAL INTO :NEW.ID_TIPO_DIFICULTAD FROM dual;
END;

----TIPO_DURACION
CREATE OR REPLACE TRIGGER tipo_duracion_trigger
BEFORE INSERT ON TIPO_DURACION
FOR EACH ROW
WHEN (NEW.ID_TIPO_DURACION IS NULL)
BEGIN
    SELECT tipo_duracion_seq.NEXTVAL INTO :NEW.ID_TIPO_DURACION FROM dual;
END;

----TIPO_CERTIFICADO
CREATE OR REPLACE TRIGGER tipo_certificado_trigger
BEFORE INSERT ON TIPO_CERTIFICADO
FOR EACH ROW
WHEN (NEW.ID_TIPO_CERTIFICADO IS NULL)
BEGIN
    SELECT tipo_certificado_seq.NEXTVAL INTO :NEW.ID_TIPO_CERTIFICADO FROM dual;
END;

----CURSOS_DISPONIBLES
CREATE OR REPLACE TRIGGER cursos_disponibles_trigger
BEFORE INSERT ON CURSOS_DISPONIBLES
FOR EACH ROW
WHEN (NEW.ID_CUR_DISPONIBLE IS NULL)
BEGIN
    SELECT cursos_disponibles_seq.NEXTVAL INTO :NEW.ID_CUR_DISPONIBLE FROM dual;
END;

----CURSOS_APROBADOS
CREATE OR REPLACE TRIGGER cursos_aprobados_trigger
BEFORE INSERT ON CURSOS_APROBADOS
FOR EACH ROW
WHEN (NEW.ID_APROBADO IS NULL)
BEGIN
    SELECT cursos_aprobados_seq.NEXTVAL INTO :NEW.ID_APROBADO FROM dual;
END;

----CONTENIDOS
CREATE OR REPLACE TRIGGER contenidos_trigger
BEFORE INSERT ON CONTENIDOS
FOR EACH ROW
WHEN (NEW.ID_CONTENIDO IS NULL)
BEGIN
    SELECT contenidos_seq.NEXTVAL INTO :NEW.ID_CONTENIDO FROM dual;
END;

----SUB_CONTENIDOS
CREATE OR REPLACE TRIGGER sub_contenidos_trigger
BEFORE INSERT ON SUB_CONTENIDOS
FOR EACH ROW
WHEN (NEW.ID_SUBCONT IS NULL)
BEGIN
    SELECT sub_contenidos_seq.NEXTVAL INTO :NEW.ID_SUBCONT FROM dual;
END;

----PREGUNTAS_CURSO
CREATE OR REPLACE TRIGGER preguntas_curso_trigger
BEFORE INSERT ON PREGUNTAS_CURSO
FOR EACH ROW
WHEN (NEW.ID_PREGUNTA IS NULL)
BEGIN
    SELECT preguntas_curso_seq.NEXTVAL INTO :NEW.ID_PREGUNTA FROM dual;
END;

----RESPUESTAS_CURSO
CREATE OR REPLACE TRIGGER respuestas_curso_trigger
BEFORE INSERT ON RESPUESTAS_CURSO
FOR EACH ROW
WHEN (NEW.ID_RESPUESTA IS NULL)
BEGIN
    SELECT respuestas_curso_seq.NEXTVAL INTO :NEW.ID_RESPUESTA FROM dual;
END;