---SCRIPT PARA BORRAR LAS TABLAS---
DROP TABLE CURSOS_APROBADOS; DROP TABLE CURSOS_DISPONIBLES; DROP TABLE OFERTAS_DISPONIBLES; DROP TABLE RESPUESTAS_OFERTAS;
DROP TABLE RESPUESTAS_CURSO; DROP TABLE SUB_CONTENIDOS; DROP TABLE CERTIFICADOS; 
DROP TABLE CONOCIMIENTOS; DROP TABLE TIPO_CONT; DROP TABLE EXP_LABORALES;
DROP TABLE LENGUAJES_PROG; DROP TABLE APTITUDES; DROP TABLE IDIOMAS; DROP TABLE FORMACIONES_ACADEMICAS;
DROP TABLE CONTENIDOS; DROP TABLE PREGUNTAS_CURSO;
DROP TABLE HOJAS_DE_VIDA;  DROP TABLE CURSOS; DROP TABLE OFERTAS_EMPLEOS;
DROP TABLE ESTUDIANTES; DROP TABLE EMPRESAS;

---TABLAS DE ESTUDIANTES---
CREATE TABLE ESTUDIANTES(
  ID_ESTUDIANTE NUMBER(10),
  TIPO_ID VARCHAR2(25),
  NOM_ESTUDIANTE VARCHAR2(50),
  APELLIDO VARCHAR2(50),
  CORREO_ESTUDIANTE VARCHAR2(50),
  FECHA_NAC DATE,
  PASSWORD_ESTUDIANTE VARCHAR2(255),
  CONSTRAINT PK_ESTUDIANTE PRIMARY KEY (ID_ESTUDIANTE)
);

---TABLAS DE HOJAS DE VIDA---
CREATE TABLE HOJAS_DE_VIDA (
  ID_HOJA_VIDA NUMBER(10),
  DESCRIPCION VARCHAR2(1000),
  TELEFONO NUMBER(10),
  DIRECCION VARCHAR2(60),
  ID_ESTUDIANTE NUMBER(10),
  CONSTRAINT PK_HOJA_VIDA PRIMARY KEY (ID_HOJA_VIDA),
  CONSTRAINT FK_HOJA_VIDA_ESTUDIANTE FOREIGN KEY (ID_ESTUDIANTE) REFERENCES ESTUDIANTES(ID_ESTUDIANTE)
);

CREATE TABLE LENGUAJES_PROG (
  ID_LENGUAJE NUMBER(10),
  NOMBRE_LENG VARCHAR2(50),
  ID_HOJAVIDA NUMBER(10),
  CONSTRAINT PK_LENGUAJE PRIMARY KEY (ID_LENGUAJE),
  CONSTRAINT FK_LENGUAJE_HOJA_VIDA FOREIGN KEY (ID_HOJAVIDA) REFERENCES HOJAS_DE_VIDA(ID_HOJA_VIDA)
);

CREATE TABLE APTITUDES (
  ID_APTITUDES NUMBER(10),
  NOMBRE_APT VARCHAR2(50),
  ID_HOJAVIDA NUMBER(10),
  CONSTRAINT PK_APTITUDES PRIMARY KEY (ID_APTITUDES),
  CONSTRAINT FK_APTITUDES_HOJA_VIDA FOREIGN KEY (ID_HOJAVIDA) REFERENCES HOJAS_DE_VIDA(ID_HOJA_VIDA)
);

CREATE TABLE IDIOMAS (
  ID_IDIOMA NUMBER(10),
  IDIOMA VARCHAR2(20),
  NIVEL VARCHAR2(20),
  ID_HOJAVIDA NUMBER(10),
  CONSTRAINT PK_IDIOMA PRIMARY KEY (ID_IDIOMA),
  CONSTRAINT FK_IDIOMA_HOJA_VIDA FOREIGN KEY (ID_HOJAVIDA) REFERENCES HOJAS_DE_VIDA(ID_HOJA_VIDA)
);

CREATE TABLE FORMACIONES_ACADEMICAS (
  ID_FORMACION NUMBER(10),
  NOM_INSTITUCION VARCHAR2(50),
  TITULO VARCHAR2(50),
  FECHA_INICIO DATE,
  FECHA_FINAL DATE,
  ID_HOJAVIDA NUMBER(10),
  CONSTRAINT PK_FORMACION PRIMARY KEY (ID_FORMACION),
  CONSTRAINT FK_FORMACION_HOJA_VIDA FOREIGN KEY (ID_HOJAVIDA) REFERENCES HOJAS_DE_VIDA(ID_HOJA_VIDA)
);

CREATE TABLE EXP_LABORALES (
  ID_EXP NUMBER(10),
  NOM_EMPRESAS VARCHAR2(50),
  TIEMPO_INICIO DATE,
  TIEMPO_FINAL DATE,
  CARGO VARCHAR2(30),
  DESCRIPCION VARCHAR2(1000),
  ID_HOJAVIDA NUMBER(10),
  CONSTRAINT PK_EXP_LABORALES PRIMARY KEY (ID_EXP),
  CONSTRAINT FK_EXP_LABORALES_HOJA_VIDA FOREIGN KEY (ID_HOJAVIDA) REFERENCES HOJAS_DE_VIDA(ID_HOJA_VIDA)
);

---TABLAS DE EMPRESAS---
CREATE TABLE EMPRESAS (
  NIT NUMBER(25),
  NOM_EMPRESA VARCHAR2(50),
  DIRECCION VARCHAR2(60),
  CORREO_EMP VARCHAR2(50),
  PASSWORD_EMP VARCHAR2(255),
  TELEFONO NUMBER(10),
  CONSTRAINT PK_EMPRESA PRIMARY KEY (NIT)
);

---TABLAS DE OFERTAS---
CREATE TABLE OFERTAS_EMPLEOS (
  ID_OFERTA NUMBER(10),
  NOMBRE_OFERTA VARCHAR2(50),
  SALARIO NUMBER(15, 2),  
  DESCRIPCION VARCHAR2(1000),
  ESTADO NUMBER(1),
  FECHA_PUB DATE,
  NIT NUMBER(25),
  CONSTRAINT PK_OFERTA PRIMARY KEY (ID_OFERTA),
  CONSTRAINT FK_OFERTA_EMPRESA FOREIGN KEY (NIT) REFERENCES EMPRESAS(NIT)
);

CREATE TABLE CONOCIMIENTOS(
  ID_CONOCIMIENTO NUMBER(10),
  NOM_CON VARCHAR2(100),
  ID_OFERTA NUMBER(10),
  CONSTRAINT PK_CONOCIMIENTO PRIMARY KEY (ID_CONOCIMIENTO),
  CONSTRAINT FK_CONOCIMIENTOS FOREIGN KEY (ID_OFERTA) REFERENCES OFERTAS_EMPLEOS(ID_OFERTA)
);

CREATE TABLE TIPO_CONT(
  ID_TIPO_CONT NUMBER(10),
  TIPO_CONT VARCHAR2(50),
  ID_OFERTA NUMBER(10),
  CONSTRAINT PK_TIPO_CONT PRIMARY KEY (ID_TIPO_CONT, ID_OFERTA), 
  CONSTRAINT FK_TIPO_CONT FOREIGN KEY (ID_OFERTA) REFERENCES OFERTAS_EMPLEOS(ID_OFERTA)
);

CREATE TABLE RESPUESTAS_OFERTAS(
  ID_RESPUESTAS_OFERTAS NUMBER(10),
  ID_OFERTA NUMBER(10),
  ID_ESTUDIANTE NUMBER(10),
  CONSTRAINT PK_RESPUESTAS_OFERTAS PRIMARY KEY (ID_RESPUESTAS_OFERTAS),
  CONSTRAINT FK_RESPUESTAS_OFERTAS FOREIGN KEY (ID_OFERTA) REFERENCES OFERTAS_EMPLEOS(ID_OFERTA),
  CONSTRAINT FK_RESPUESTAS_ESTUDIANTES FOREIGN KEY (ID_ESTUDIANTE) REFERENCES ESTUDIANTES(ID_ESTUDIANTE)
);

CREATE TABLE OFERTAS_DISPONIBLES (
    ID_OFER_DISPONIBLE NUMBER(10),
    ACTIVACION NUMBER(1),
    ID_OFERTA NUMBER(10),
    ID_ESTUDIANTE NUMBER(10),
    CONSTRAINT PK_OFER_DISPONIBLE PRIMARY KEY (ID_OFER_DISPONIBLE),
    CONSTRAINT FK_OFER_DISPONIBLE_ESTUDIANTE FOREIGN KEY (ID_ESTUDIANTE) REFERENCES ESTUDIANTES(ID_ESTUDIANTE),
    CONSTRAINT FK_OFER_DISPONIBLE_OFERTA FOREIGN KEY (ID_OFERTA) REFERENCES OFERTAS_EMPLEOS(ID_OFERTA)
);

---TABLAS DE CURSOS---
CREATE TABLE CURSOS (
  ID_CURSO NUMBER(10),
  NOM_CURSO VARCHAR2(50),
  PRECIO NUMBER(15),
  DIFICULTAD VARCHAR2(10),
  LENGUAJE VARCHAR2(25),
  TIEMPO VARCHAR2(15),
  CERTIFICADO NUMBER(1),
  DESCRIPCION VARCHAR2(1000),
  URL_IMAGEN VARCHAR2(20),
  CONSTRAINT PK_CURSO PRIMARY KEY (ID_CURSO)
);

CREATE TABLE CURSOS_DISPONIBLES (
    ID_CUR_DISPONIBLE NUMBER(10),
    ACTIVACION NUMBER(1),
    ID_CURSO NUMBER(10),
    ID_ESTUDIANTE NUMBER(10),
    CONSTRAINT PK_CUR_DISPONIBLE PRIMARY KEY (ID_CUR_DISPONIBLE),
    CONSTRAINT FK_CUR_DISPONIBLE_ESTUDIANTE FOREIGN KEY (ID_ESTUDIANTE) REFERENCES ESTUDIANTES(ID_ESTUDIANTE),
    CONSTRAINT FK_CUR_DISPONIBLE_CURSO FOREIGN KEY (ID_CURSO) REFERENCES CURSOS(ID_CURSO)
);

CREATE TABLE CURSOS_APROBADOS (
  ID_APROBADO NUMBER(10),
  ID_CURSO NUMBER(10),
  ID_ESTUDIANTE NUMBER(10),
  CONSTRAINT PK_APROBADO PRIMARY KEY (ID_APROBADO),
  CONSTRAINT FK_APROBADOS_CURSO FOREIGN KEY (ID_CURSO) REFERENCES CURSOS(ID_CURSO),
  CONSTRAINT FK_APROBADOS_ESTUDIANTE FOREIGN KEY (ID_ESTUDIANTE) REFERENCES ESTUDIANTES(ID_ESTUDIANTE)
);

CREATE TABLE CONTENIDOS (
  ID_CONTENIDO NUMBER(10),
  NOM_CONTENIDO VARCHAR2(50),
  ID_CURSO NUMBER(10),
  CONSTRAINT PK_CONTENIDO PRIMARY KEY (ID_CONTENIDO),
  CONSTRAINT FK_CONTENIDO_CURSO FOREIGN KEY (ID_CURSO) REFERENCES CURSOS(ID_CURSO)
);

CREATE TABLE SUB_CONTENIDOS (
  ID_SUBCONT NUMBER(10),
  NOM_SUBCONT VARCHAR2(50),
  URL_CONT VARCHAR2(1000),
  ID_CONTENIDO NUMBER(10),
  CONSTRAINT PK_SUBCONT PRIMARY KEY (ID_SUBCONT),
  CONSTRAINT FK_SUBCONT_CONTENIDO FOREIGN KEY (ID_CONTENIDO) REFERENCES CONTENIDOS(ID_CONTENIDO)
);

CREATE TABLE PREGUNTAS_CURSO (
  ID_PREGUNTA NUMBER(10),
  PREGUNTA_TEXT VARCHAR2(1000),
  ID_CURSO NUMBER(10),
  CONSTRAINT PK_PREGUNTA_CURSO PRIMARY KEY (ID_PREGUNTA),
  CONSTRAINT FK_PREGUNTAS_CURSO FOREIGN KEY (ID_CURSO) REFERENCES CURSOS(ID_CURSO)
);

CREATE TABLE RESPUESTAS_CURSO (
  ID_RESPUESTA NUMBER(10),
  RESPUESTA_TEXT VARCHAR2(1000),
  VALIDACION NUMBER(1),
  ID_PREGUNTA NUMBER(10),
  CONSTRAINT PK_RESPUESTA_CURSO PRIMARY KEY (ID_RESPUESTA),
  CONSTRAINT FK_RESPUESTA_PREGUNTA_CURSO FOREIGN KEY (ID_PREGUNTA) REFERENCES PREGUNTAS_CURSO(ID_PREGUNTA)
);